"""empty message

Revision ID: b8df8e45d215
Revises: 
Create Date: 2020-04-12 02:11:00.471777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8df8e45d215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=True),
    sa.Column('latex', sa.String(length=4096), nullable=True),
    sa.Column('image_hrefs_json', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('latex', sa.String(length=4096), nullable=True),
    sa.Column('image_hrefs_json', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='hintstatus'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hint')
    op.drop_table('task')
    # ### end Alembic commands ###
