"""empty message

Revision ID: c172a7552a7f
Revises: 
Create Date: 2020-04-12 00:15:42.633167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c172a7552a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=True),
    sa.Column('latex', sa.String(length=4096), nullable=True),
    sa.Column('image_hrefs_json', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hint_id'], ['hint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    op.drop_table('hint')
    op.drop_table('task')
    # ### end Alembic commands ###
