"""empty message

Revision ID: dab3d39f571f
Revises: 
Create Date: 2020-05-03 18:24:26.452061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab3d39f571f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('base_number', sa.String(length=16), nullable=True),
    sa.Column('task_number', sa.String(length=16), nullable=True),
    sa.Column('latex', sa.String(length=4096), nullable=True),
    sa.Column('image_ids_json', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=True),
    sa.Column('auth_token', sa.String(length=512), nullable=True),
    sa.Column('color_background_primary', sa.String(length=16), nullable=True),
    sa.Column('color_background_secondary', sa.String(length=16), nullable=True),
    sa.Column('color_foreground_primary', sa.String(length=16), nullable=True),
    sa.Column('color_foreground_secondary', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('latex', sa.String(length=4096), nullable=True),
    sa.Column('image_ids_json', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='hintstatus'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('hint')
    op.drop_table('user')
    op.drop_table('task')
    # ### end Alembic commands ###
